insert into public.students (name)
values
  ('Muhammad Umar Iftikhar'),
  ('Areeba Naeem'),
  ('Shiza Najeeb'),
  ('Ubaid Ur Rehman'),
  ('Warda Aziz'),
  ('Syed Hashir Ayaz'),
  ('Fatima Wajahat'),
  ('Kashaf Fatima'),
  ('Muhammad Hassaan Mansur'),
  ('Maadehah Asif'),
  ('Husnain Akram'),
  ('Rubban Iftikhar Ahmed'),
  ('Anhar Munir'),
  ('Muhammad Abdullah Iqbal'),
  ('Hania Bashir'),
  ('Abdur Rehman'),
  ('Muhammad Safi Ur Rehman'),
  ('Syed Haroon Rasheed'),
  ('Muhammad Bilal Raza Attari'),
  ('Abdul Moiz Hassan'),
  ('Esha Riaz'),
  ('Muhammad Sheryar Ali'),
  ('Abdullah Tariq'),
  ('Abdul Faheem'),
  ('Humair Naseer'),
  ('Noor Junaina'),
  ('Syed Muhammad Pasha'),
  ('Muhammad Hammad Ur Rehman'),
  ('Muhammad Ahtisham'),
  ('Muhammad Tayyab'),
  ('Hassan'),
  ('Syed Burhan Haider'),
  ('Maham Imran'),
  ('Faiz Ur Rahman'),
  ('Muhammad Usman Ghani'),
  ('Saif Ur Rehman'),
  ('Safdar Jan'),
  ('Sajjad Ahmed')
on conflict (name) do nothing;

insert into public.titles (title_name, display_order)
values
  ('Best Smile', 1),
  ('Most Helpful', 2),
  ('Class Comedian', 3),
  ('Most Likely to Be CEO', 4),
  ('Most Likely to Build a Startup', 5),
  ('Best Problem Solver', 6),
  ('Most Likely to Survive Production Bugs', 7),
  ('Best Dressed', 8),
  ('Most Creative Mind', 9),
  ('Most Calm Under Pressure', 10),
  ('Most Likely to Become a Great Team Lead', 11),
  ('Best Presentation Skills', 12),
  ('Most Reliable', 13),
  ('Quiet Genius', 14),
  ('Best Debugger', 15),
  ('Most Likely to Become a Researcher', 16),
  ('Best Laugh', 17),
  ('Most Likely to Work at Google', 18),
  ('Best Collaborator', 19),
  ('Future Tech Icon', 20)
on conflict (title_name) do update
set display_order = excluded.display_order;
